### ISSUE TITLE
Feature Request: Price API

### ISSUE THREAD

**Issue by benjaminweb** [juliuste/meinfernbus#7]
Perspective: Integrate in https://bahn.guru, use affiliate links to Flixbus booking system.

**Comment by juliuste** [comment]
Even though I'd really love to make this happen, I sadly don't have the courage to do so at the moment. Right now the website is operating under facit consent by Deutsche Bahn (since it's using a rather 'special' API 😉). Currently DB is pretty clearly benefitting from the service since they just gain additional customers. But once I add a competitor, this point might be way harder to make which could actually lead to conflict with DB. That's why I'm hesitating to add this feature. By the way: I basically already added it (as you can see [here](https://github.com/juliuste/bahn.guru/tree/master/db-meinfernbus)), but simply didn't flip the switch yet.

**Comment by juliuste** [comment]
Dont worry, I didn't forget about your mail, just didn't find the time to write a detailled answer, but I'll get back to you soon. But let me close this issue for now (:
